/**
 * Country Commerce Data
 * Currency symbols and codes for country detection
 */

// Currency symbols and codes to countries
export const CURRENCY_TO_COUNTRY: Record<string, string> = {
  "$": "United States",
  "US$": "United States",
  "USD": "United States",
  "A$": "Australia",
  "AU$": "Australia",
  "AUD": "Australia",
  "C$": "Canada",
  "CA$": "Canada",
  "CAD": "Canada",
  "£": "United Kingdom",
  "GBP": "United Kingdom",
  "€": "International",
  "EUR": "International",
  "¥": "Japan",
  "JP¥": "Japan",
  "JPY": "Japan",
  "CN¥": "China",
  "CNY": "China",
  "RMB": "China",
  "₹": "India",
  "Rs": "India",
  "INR": "India",
  "₨": "Pakistan",
  "PKR": "Pakistan",
  "LKR": "Sri Lanka",
  "NPR": "Nepal",
  "₩": "South Korea",
  "KRW": "South Korea",
  "₽": "Russia",
  "RUB": "Russia",
  "R$": "Brazil",
  "BRL": "Brazil",
  "R": "South Africa",
  "ZAR": "South Africa",
  "CHF": "Switzerland",
  "Fr": "Switzerland",
  "SEK": "Sweden",
  "kr": "Sweden",
  "NOK": "Norway",
  "DKK": "Denmark",
  "PLN": "Poland",
  "zł": "Poland",
  "₺": "Turkey",
  "TRY": "Turkey",
  "TL": "Turkey",
  "MXN": "Mexico",
  "Mex$": "Mexico",
  "ARS": "Argentina",
  "AR$": "Argentina",
  "CLP": "Chile",
  "COP": "Colombia",
  "PEN": "Peru",
  "S/": "Peru",
  "THB": "Thailand",
  "฿": "Thailand",
  "MYR": "Malaysia",
  "RM": "Malaysia",
  "SGD": "Singapore",
  "S$": "Singapore",
  "IDR": "Indonesia",
  "Rp": "Indonesia",
  "PHP": "Philippines",
  "₱": "Philippines",
  "VND": "Vietnam",
  "₫": "Vietnam",
  "NZD": "New Zealand",
  "NZ$": "New Zealand",
  "HKD": "Hong Kong",
  "HK$": "Hong Kong",
  "TWD": "Taiwan",
  "NT$": "Taiwan",
  "AED": "United Arab Emirates",
  "SAR": "Saudi Arabia",
  "SR": "Saudi Arabia",
  "QAR": "Qatar",
  "KWD": "Kuwait",
  "BHD": "Bahrain",
  "OMR": "Oman",
  "ILS": "Israel",
  "₪": "Israel",
  "EGP": "Egypt",
  "MAD": "Morocco",
  "NGN": "Nigeria",
  "₦": "Nigeria",
  "KES": "Kenya",
  "KSh": "Kenya",
  "GHS": "Ghana",
  "GH₵": "Ghana",
  "TZS": "Tanzania",
  "UGX": "Uganda",
  "ZMW": "Zambia",
  "BWP": "Botswana",
  "P": "Botswana",
};
