// Industry options for onboarding dropdown and auto-fill validation
// Sorted alphabetically for consistent UX

export const INDUSTRIES = [
  "Agriculture / Farming",
  "Art / Design / Creative Services",
  "Automotive / Transportation",
  "Baby / Kids / Parenting",
  "B2B / Business Services",
  "Beauty / Personal Care",
  "Blockchain / Web3",
  "Construction / Architecture",
  "Consulting / Professional Services",
  "Cybersecurity",
  "E-commerce / Retail",
  "EdTech / Education",
  "Energy / Sustainability / Green Tech",
  "Events / Weddings",
  "Fashion / Apparel / Luxury",
  "FinTech / Finance",
  "Food & Beverage / Restaurants",
  "Gaming / Entertainment",
  "Government / Public Sector",
  "HealthTech / Healthcare",
  "Home Improvement",
  "Human Resources / Staffing",
  "Insurance",
  "Legal / Compliance",
  "Logistics / Supply Chain",
  "Manufacturing / Industrial",
  "Marketing / Advertising",
  "Media / Publishing",
  "Mental Health / Wellness",
  "Music / Audio",
  "Non-profit / NGO",
  "Nutrition / Diet",
  "Other",
  "Pet Industry",
  "Pharmaceuticals / Biotech",
  "Photography / Videography",
  "Real Estate",
  "Research / Science",
  "SaaS / Software",
  "Security / Defense",
  "Senior Care",
  "Sports / Fitness / Recreation",
  "Telecommunications",
  "Travel / Hospitality",
  "Utilities",
  "Waste Management / Recycling",
  "Wholesale / Distribution",
  "Writing / Content",
] as const;

export type Industry = typeof INDUSTRIES[number];